pre_app_deploy:
 execs:
  Configure Wordpress:
   name: Configure Wordpress
   command: |
     #!/usr/bin/env bash
     . ${APPLICATION_SECRETS_FILE}
    
     config_file="wp-config.php"
     cp wp-config-sample.php ${config_file}

     sed -i -- 's/database_name_here/'"${database_name}"'/g' ${config_file}
     sed -i -- 's/username_here/'"${database_user}"'/g' ${config_file}
     sed -i -- 's/password_here/'"${user_password}"'/g' ${config_file}

post_app_deploy:
 execs:
  Restart apache:
   name: Restart apache
   command: |
     #!/usr/bin/env bash
     chown -RL www-data:www-data /var/www/html/wordpress
     service apache2 restart
