exec_once:
 files:
  /etc/apache2/sites-enabled/wordpress.conf:
    name: wordpress.conf
    path: /etc/apache2/sites-enabled/
    mode: "0644"
    owner: root
    group: root
    content: |
      <VirtualHost *:80>
        DocumentRoot /var/www/html/wordpress
        <Directory /var/www/html/wordpress>
          AllowOverride All
          Order Allow,Deny
          Allow from All
        </Directory>

        CustomLog /var/log/apache2/access.log combined
        ErrorLog /var/log/apache2/error.log

      </VirtualHost>
 execs:
  Remove default apache config file:
   name: Remove default apache config file
   command: |
     rm -f /etc/apache2/sites-enabled/000-default.conf

pre_app_deploy:
 execs:
  Configure Wordpress:
   name: Configure Wordpress
   command: |
     #!/usr/bin/env bash
     . /etc/profile.d/azure_secrets.sh
    
     config_file="wp-config.php"
     cp wp-config-sample.php ${config_file}

     sed -i -- "s/database_name_here/${MYSQL_DATABASE}/g" ${config_file}
     sed -i -- "s/username_here/${MYSQL_USER}/g" ${config_file}
     sed -i -- "s/password_here/${MYSQL_PASSWORD}/g" ${config_file}

post_app_deploy:
 execs:
  Restart apache:
   name: Restart apache
   command: |
     #!/usr/bin/env bash
     chown -RL www-data:www-data /var/www/html/wordpress
     service apache2 restart
